### ISSUE TITLE
oracle docker-compose for multiple containers 

### ISSUE THREAD

**Issue by ict-singapore** [oracle/docker-images#1227]
Im trying to create multiple containers for multiple users in a classroom by using docker-compose each exposing separate port for access. the sample docker-compose.yml is below : 

```

version: '2'
  services:
  db-1:
  image: oracle/database:12.2.0.1-se2
  ports:
  - 15211:1521
  - 55001:5500
  environment:
  - ORACLE_SID=ORCLCDB
  - ORACLE_PDB=ORCLPDB1
  - ORACLE_PWD=C@nn0ts@y1
  - ORACLE_CHARACTERSET=AL32UTF8
  db-2:
  image: oracle/database:12.2.0.1-se2
  ports:
  - 15212:1521
  - 55002:5500
  environment:
  - ORACLE_SID=ORCLCDB
  - ORACLE_PDB=ORCLPDB1
  - ORACLE_PWD=C@nn0ts@y1
  - ORACLE_CHARACTERSET=AL32UTF8
```

As per the sample if i add the line volumes:
`/home/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.` , there is an error creating the database and it stops. 

What will be a better way for volumes to be added.  Also, if i need to create user and assign permissions to the accounts , is there a script available to automate the process
