### ISSUE TITLE
OGG lacks my Local deployment on the second start

### ISSUE THREAD

**Issue by alesana-san** [oracle/docker-images#1277]
Hi!

I try to create a simple OGG Microservices container using the following `docker-compose` file:
`````
version: '3'
services:
  ogg:
    image: oracle/goldengate-microservices:12.3.0.1.4
    container_name: ogg-12.3.0.1.4
    environment:
      - OGG_SCHEMA=oggadmin
      - OGG_ADMIN=oggadmin
      - OGG_ADMIN_PWD=q12345678
      - OGG_DEPLOYMENT=Local
    ports:
      - 9100-9104:9100-9104
    volumes:
      - T:\docker-data\ogg\conf:/u02/ogg/Local/etc/conf
      - T:\docker-data\ogg\trail:/u02/ogg/Local/var/lib/data
    cap_add:
      - SYS_RESOURCE
`````

I use Docker for Windows so I have a path `T:\docker-data\ogg\conf` for configs and a path for trail files `T:\docker-data\ogg\trail` located on a host machine.
The very first start seems ok. Here's `docker logs` output: [first_start.log](https://github.com/oracle/docker-images/files/3168826/first_start.log). And I can see my `Local` deployment: 
![ogg1](https://user-images.githubusercontent.com/35428099/57567656-4ee75800-73e5-11e9-85a7-781d903f9d68.png)
Then I `docker-compose down` my deployment and `up` again. Since the second start I don't see my `Local` deployment: 
![ogg2](https://user-images.githubusercontent.com/35428099/57567667-78a07f00-73e5-11e9-8039-849ec386bbed.png)
Here's a `docker logs` output for the second start: 
[second_start.log](https://github.com/oracle/docker-images/files/3168830/second_start.log).

I'm expecting to see my configuration saved between `up`s and `down`s. I'm not good at `OGG` file structure and maybe I have to provide some other paths to several files in order to make them persistent using `volume`.
