### ISSUE TITLE
OGG container fails to start in an air-gapped system

### ISSUE THREAD

**Issue by alesana-san** [oracle/docker-images#1278]
Hi!

I try to run an `OGG Microservices` container using the following `docker-compose` file:
`````
version: '3'
services:
  ogg:
    image: oracle/goldengate-microservices:12.3.0.1.4
    container_name: ogg-12.3.0.1.4
    environment:
      - OGG_SCHEMA=oggadmin
      - OGG_ADMIN=oggadmin
      - OGG_ADMIN_PWD=q12345678
      - OGG_DEPLOYMENT=Local
    ports:
      - 9100-9104:9100-9104
    volumes:
      - T:\docker-data\ogg\conf:/u02/ogg/Local/etc/conf
      - T:\docker-data\ogg\trail:/u02/ogg/Local/var/lib/data
    cap_add:
      - SYS_RESOURCE
`````
Everything looks fine, here's `docker logs` output for this container: [connected_start.log](https://github.com/oracle/docker-images/files/3168855/connected_start.log)
Then I switch off WiFi on my laptop and start again. Unfortunately container fails to start: [air_gapped_start.log](https://github.com/oracle/docker-images/files/3168858/air_gapped_start.log)
I can see that `OGG` tries to use container ID as a hostname and fails to start.
I use `Docker for Windows`.
