### ISSUE TITLE
Docker image with version 11.2.0.3.0 

### ISSUE THREAD

**Issue by emli** [oracle/docker-images#1516]
Hi there!

Is there image with version 11.2.0.3.0? I couldn't file docker image with that version. Additionally it would be nice if I can provide database name,username,password in docker-compose file.
Provided example follow
```
version: '2'
services:
  database:
    image: oracle/database:12.1.0.2-ee
    volumes:
      - /home/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    environment:
            ORACLE_USER: dummy
            ORACLE_PASSWORD: dummy
            ORACLE_DB: dummy

```
