### ISSUE TITLE
Oracle 12.2.0.1 fails to start in Kubernetes

### ISSUE THREAD

**Issue by marklcg** [oracle/docker-images#1527]
I was able to build the Oracle database 12.2.0.1 docker image and successfully run the container on Windows 10 with docker desktop.  However, when I attempt to deploy the same image to Kubernetes, it fails to start successfully with the output below.  I've also include the manifest used to deploy the container.  

**Logs**
```txt
ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: XXXXXX

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 14-FEB-2020 16:18:45

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/oracle-784d4789d-m5tdb/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                14-FEB-2020 16:18:45
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/oracle-784d4789d-m5tdb/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[WARNING] [DBT-10102] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
   CAUSE: The database should be registered with a listener in order to access the EM DB Express URL.
   ACTION: Select a listener to be registered or created with the database.
Copying database files
1% complete
13% complete
25% complete
Creating and starting Oracle instance
DBCA Operation failed.
Look at the log file "/opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log" for further details.
[ 2020-02-14 16:19:01.973 UTC ] Copying database files
DBCA_PROGRESS : 1%
DBCA_PROGRESS : 13%
DBCA_PROGRESS : 25%
[ 2020-02-14 16:19:22.973 UTC ] Creating and starting Oracle instance
[ 2020-02-14 16:19:31.699 UTC ] ORA-01503: CREATE CONTROLFILE failed
ORA-01565: error in identifying file '/opt/oracle/oradata/ORCLCDB/sysaux01.dbf'
ORA-27037: unable to obtain file status

[ 2020-02-14 16:19:31.702 UTC ] ORA-01503: CREATE CONTROLFILE failed
ORA-01565: error in identifying file '/opt/oracle/oradata/ORCLCDB/sysaux01.dbf'
ORA-27037: unable to obtain file status

[ 2020-02-14 16:19:36.578 UTC ] DBCA_PROGRESS : DBCA Operation failed.

SQL*Plus: Release 12.2.0.1.0 Production on Fri Feb 14 16:19:36 2020

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Connected to an idle instance.

SQL>    ALTER SYSTEM SET control_files='/opt/oracle/oradata/ORCLCDB/control01.ctl' scope=spfile
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL>    ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> BEGIN DBMS_XDB_CONFIG.SETGLOBALPORTENABLED (TRUE); END;

*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> Disconnected
mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/spfileORCLCDB.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/orapwORCLCDB': No such file or directory
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
/opt/oracle/checkDBStatus.sh: line 26: sqlplus: command not found
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
GROUP 2 ('/opt/oracle/oradata/ORCLCDB/redo02.log') SIZE 200M,
GROUP 3 ('/opt/oracle/oradata/ORCLCDB/redo03.log') SIZE 200M RESETLOGS...
2020-02-14T16:19:32.295382+00:00
Shutting down instance (abort) (OS id: 628)
License high water mark = 1
USER (ospid: 628): terminating the instance
2020-02-14T16:19:33.371684+00:00
Instance terminated by USER, pid = 628
2020-02-14T16:19:33.527673+00:00
Instance shutdown complete (OS id: 628)
```

**Deployment**
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: oracle-test
  name: oracle
  labels:
    app: oracle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oracle
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 54321
        runAsGroup: 54322
        fsGroup: 54322
      containers:
      - image: nexus.[redacted].org:5000/pipeline/oracle/database:12.2.0.1-se2
        imagePullPolicy: IfNotPresent
        name: oracle
        env:
        - name: ORACLE_PWD
          valueFrom:
            secretKeyRef:
              name: oracle-secret
              key: password
        ports:
          - containerPort: 1521
            name: sqlnet
          - containerPort: 5500
            name: oem
        resources:
          limits:
            cpu: 1
            memory: 6Gi
          requests:
            cpu: 1
            memory: 2Gi
        volumeMounts:
          - name: data
            mountPath: /opt/oracle/oradata
      volumes:
      - name: data
        emptyDir: {}
```
