### ISSUE TITLE
Cannot start 18.4.0 XE on k8s

### ISSUE THREAD

**Issue by mikosh75** [oracle/docker-images#1554]
Hello,
I have built the Oracle Database 18.4.0 XE docker image successfully.
Then i tried to run it in a k8s AKS cluster (v1.14.8) with this deployment file

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exg-oradb
spec:
  selector:
    matchLabels:
      app: exg-oradb
  template:
    metadata:
      labels:
        app: exg-oradb
    spec:
      containers:
        - name: exg-oradb
          image: myregistry/exg-oradb:18.4.0-xe
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          ports:
            - containerPort: 5500
            - containerPort: 1521
          env:
            - name: ORACLE_PWD
              value: xxx
          volumeMounts:
          - mountPath: /opt/oracle/oradata
            name: oradata
      volumes:
        - name: oradata
          persistentVolumeClaim:
            claimName: disk-oradata-18xe-pvc
```

The pvc is correctly bound to an 8GB premium SSD disk, and volume is correctly mounted in the running container.
But when container starts, i've this error log

```exg-oradb-579fb78599-hjqmv ORACLE PASSWORD FOR SYS AND SYSTEM: xxx
exg-oradb-579fb78599-hjqmv Specify a password to be used for database accounts. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9]. Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:
exg-oradb-579fb78599-hjqmv Confirm the password:
exg-oradb-579fb78599-hjqmv Configuring Oracle Listener.
exg-oradb-579fb78599-hjqmv Listener configuration succeeded.
exg-oradb-579fb78599-hjqmv Configuring Oracle Database XE.
exg-oradb-579fb78599-hjqmv Enter SYS user password: 
exg-oradb-579fb78599-hjqmv ****************
exg-oradb-579fb78599-hjqmv Enter SYSTEM user password: 
exg-oradb-579fb78599-hjqmv *******************
exg-oradb-579fb78599-hjqmv Enter PDBADMIN User Password: 
exg-oradb-579fb78599-hjqmv ****************
exg-oradb-579fb78599-hjqmv Prepare for db operation
exg-oradb-579fb78599-hjqmv 7% complete
exg-oradb-579fb78599-hjqmv Copying database files
exg-oradb-579fb78599-hjqmv 29% complete
exg-oradb-579fb78599-hjqmv Creating and starting Oracle instance
exg-oradb-579fb78599-hjqmv [FATAL] ORA-01503: CREATE CONTROLFILE failed
exg-oradb-579fb78599-hjqmv ORA-01565: error in identifying file '/opt/oracle/oradata/XE/sysaux01.dbf'
exg-oradb-579fb78599-hjqmv ORA-27037: unable to obtain file status
exg-oradb-579fb78599-hjqmv 
exg-oradb-579fb78599-hjqmv 43% complete
exg-oradb-579fb78599-hjqmv 100% complete
exg-oradb-579fb78599-hjqmv [FATAL] ORA-01503: CREATE CONTROLFILE failed
exg-oradb-579fb78599-hjqmv ORA-01565: error in identifying file '/opt/oracle/oradata/XE/sysaux01.dbf'
exg-oradb-579fb78599-hjqmv ORA-27037: unable to obtain file status
exg-oradb-579fb78599-hjqmv 
exg-oradb-579fb78599-hjqmv 29% complete
exg-oradb-579fb78599-hjqmv 7% complete
exg-oradb-579fb78599-hjqmv 0% complete
exg-oradb-579fb78599-hjqmv Look at the log file "/opt/oracle/cfgtoollogs/dbca/XE/XE.log" for further details.
exg-oradb-579fb78599-hjqmv 
exg-oradb-579fb78599-hjqmv Database configuration failed. Check logs under '/opt/oracle/cfgtoollogs/dbca'.
exg-oradb-579fb78599-hjqmv mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/spfileXE.ora': No such file or directory
exg-oradb-579fb78599-hjqmv mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/orapwXE': No such file or directory
exg-oradb-579fb78599-hjqmv ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
exg-oradb-579fb78599-hjqmv information is not available for the current user ID .
exg-oradb-579fb78599-hjqmv You can set ORACLE_BASE manually if it is required.
exg-oradb-579fb78599-hjqmv Resetting ORACLE_BASE to its previous value or ORACLE_HOME
exg-oradb-579fb78599-hjqmv The Oracle base remains unchanged with value /opt/oracle
exg-oradb-579fb78599-hjqmv #####################################
exg-oradb-579fb78599-hjqmv ########### E R R O R ###############
exg-oradb-579fb78599-hjqmv DATABASE SETUP WAS NOT SUCCESSFUL!
exg-oradb-579fb78599-hjqmv Please check output for further info!
exg-oradb-579fb78599-hjqmv ########### E R R O R ###############
exg-oradb-579fb78599-hjqmv #####################################
exg-oradb-579fb78599-hjqmv The following output is now a tail of the alert.log:
exg-oradb-579fb78599-hjqmv GROUP 2 ('/opt/oracle/oradata/XE/redo02.log') SIZE 200M,
exg-oradb-579fb78599-hjqmv GROUP 3 ('/opt/oracle/oradata/XE/redo03.log') SIZE 200M RESETLOGS...
exg-oradb-579fb78599-hjqmv 2020-03-21T23:37:25.729867+00:00
exg-oradb-579fb78599-hjqmv Shutting down instance (abort) (OS id: 722)
exg-oradb-579fb78599-hjqmv License high water mark = 1
exg-oradb-579fb78599-hjqmv USER (ospid: 722): terminating the instance
exg-oradb-579fb78599-hjqmv 2020-03-21T23:37:26.775303+00:00
exg-oradb-579fb78599-hjqmv Instance terminated by USER, pid = 722
exg-oradb-579fb78599-hjqmv 2020-03-21T23:37:26.877255+00:00
exg-oradb-579fb78599-hjqmv Instance shutdown complete (OS id: 722)
```

This is XE.log
 
```
bash-4.2# cat /opt/oracle/cfgtoollogs/dbca/XE/XE.log
[ 2020-03-21 23:35:43.237 UTC ] Prepare for db operation
DBCA_PROGRESS : 7%
[ 2020-03-21 23:35:43.427 UTC ] Copying database files
DBCA_PROGRESS : 29%
[ 2020-03-21 23:37:14.999 UTC ] Creating and starting Oracle instance
[ 2020-03-21 23:37:25.258 UTC ] [FATAL] ORA-01503: CREATE CONTROLFILE failed
ORA-01565: error in identifying file '/opt/oracle/oradata/XE/sysaux01.dbf'
ORA-27037: unable to obtain file status

DBCA_PROGRESS : 43%
DBCA_PROGRESS : 100%
[ 2020-03-21 23:37:25.329 UTC ] [FATAL] ORA-01503: CREATE CONTROLFILE failed
ORA-01565: error in identifying file '/opt/oracle/oradata/XE/sysaux01.dbf'
ORA-27037: unable to obtain file status

DBCA_PROGRESS : 29%
DBCA_PROGRESS : 7%
DBCA_PROGRESS : 0%
```

"Copying database files" line is stuck for more than 1 minute.
I don't know what could be the issue...
Just as a side note, some days ago i tried to run an 11.2.0.2-xe image, and that started successfully.
Many thanks!
Michele
