### ISSUE TITLE
After First Start 19.3.0 Enterprise Edition Forgets Privileged User Password

### ISSUE THREAD

**Issue by PeterMerkert** [oracle/docker-images#1671]
## Problem

Hi, I recently switched to Windows and when I run my docker container with an Oracle 19.3.0. Enterprise Edition the second time, it will deny access to user `SYS` with `ORA-01017: invalid username/password; login denied` through SQL developer. The first startup of the container still let me connect to it with my provided password in the setup.
The whole process works fine on MacOS.

Maybe I missed something in the setup windows specific?

Even changing the password explicitly again in my running container with the `setPassword` script does not have any effect. Might be related to https://github.com/oracle/docker-images/issues/1641?

## Reproduction

The reproduction should be as follows:
1. Cloned this repo, downloaded the OracleDB image, places it in the 19.3.0 folder, and then `./buildDockerImage.sh -v 19.3.0 -e`
2. Running `docker-compose up` with the following docker-compose.yaml:
```yaml
version: '2'
services:
  database:
    container_name: rtrcd.oracledb-1930-ee
    image: oracle/database:19.3.0-ee
    environment:
      ORACLE_PWD: R3rt4C3dL0ve5Or4cle
      ORACLE_PDB: RETRACEDPDB
      ORACLE_SID: RETRACEDSID
      ORACLE_CHARACTERSET: AL32UTF8 # Explicit default
    volumes:
      - ./oracle/db/oradata:/opt/oracle/oradata # To persist the database after shutting down
      - ./oracle/db/setup:/opt/oracle/scripts/setup # Scripts to be executed after setup
    ports:
      - 1521:1521
      - 5500:5500
```
The scripts directory contain the following additional user creation process:
```sql
ALTER SESSION SET CONTAINER=RETRACEDPDB;
CREATE USER RETRACED IDENTIFIED BY R3rt4C3dL0ve5Or4cle;
GRANT CREATE ANY MATERIALIZED VIEW, CREATE JOB, CONNECT, RESOURCE, CREATE ANY VIEW TO RETRACED;
GRANT UNLIMITED TABLESPACE TO RETRACED;
ALTER USER RETRACED QUOTA UNLIMITED ON USERS;

exit;
```
3. Wait till DB is ready to use.
4. Connect with SQL developer to user user `SYS` and password `R3rt4C3dL0ve5Or4cle`. Works.
5. Stop the oracle container. Run again `docker-compose up`. Wait till DB is ready to use.
6. Connect with SQL developer to user user `SYS` and password `R3rt4C3dL0ve5Or4cle`. Denied.

![Image 004](https://user-images.githubusercontent.com/37897665/88888027-3069b880-d246-11ea-9e6a-5cff623173f0.png)
