### ISSUE TITLE
dbca installation failed due to memory issue on kubernetes cluster

### ISSUE THREAD

**Issue by slipu120** [oracle/docker-images#1728]
Hi,

I am trying to install oracle19c on kubernetes but it's failing with memory issue. I observed temporary init file created (SEEDDB)  with SGA=170GB which crashing the DB. I am using below YAML file for setup. Please suggest

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle19c 
#  namespace: oracle-namespace
  labels:
    app: database
    version: 19.3.0.1
spec:
  serviceName: "oracle19c"
  replicas: 1
  selector:
    matchLabels:
      app: database
      version: 19.3.0.1
  template:
    metadata:
      name: oracle19c
      labels:
        app: database
        version: 19.3.0.1
    spec:
      #priorityClassName: p3
      securityContext:
        fsGroup: 54321
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
        - name: oracle19c
          image: [redacted]/[redacted]/oracle/database:19.3.0.1-ee
          command:
          - /opt/oracle/runOracle.sh
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "5"
              #phemeral-storage: 10Gi
              memory: 30Gi
            requests:
              cpu: "2"
              #ephemeral-storage: 10Gi
              memory: 10Gi
          ports:
            - name: listener
              containerPort: 1521
            - name: oemexpress
              containerPort: 5500
          volumeMounts:
            - name: dshm
              mountPath: "/dev/shm"
            - name: ora-data193
              mountPath: "/opt/oracle/oradata"
            - name: ora-setup193
              mountPath: "/opt/oracle/scripts/setup"
            - name: ora-startup193
              mountPath: "/opt/oracle/scripts/startup"
  volumeClaimTemplates:
  - metadata:
      name: ora-startup193 
    spec:
      storageClassName: scaleio
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: ora-setup193
    spec:
      storageClassName: scaleio
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: ora-data193
    spec:
      storageClassName: scaleio
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
```

Edited for formatting and to redact identifying information.
