### ISSUE TITLE
SQL files not executing on Oracle 12C Database startup

### ISSUE THREAD

**Issue by zarif98sjs** [oracle/docker-images#1933]
I am using Oracle Database Enterprise Edition and this is my docker-compose

```
version: '3'
services:
    db:
      image: store/oracle/database-enterprise:12.2.0.1
      restart: "unless-stopped"
      ports:
        - 1523:1521
        - 5501:5500
      volumes:
        - ./setup-scripts:/opt/oracle/scripts/setup
        - ./dump:/opt/oracle/dump
      environment: 
        - "ORACLE_PWD=oracle"
```

When I use `docker-compose up` my sql files are copied to `/opt/oracle/scripts/setup` but the sql files are not executed. What could be the possible reason ? "ORACLE_PWD=oracle" doesn't seem to work also. I have to use the default password `Oradoc_db1`

**Comment by AmedeeBulle** [comment]
It is working for me as expected...

This is my compose file:

```
version: '3'
services:
    db:
      image: oracledb:12.2.0.1
      restart: "unless-stopped"
      ports:
        - 1523:1521
        - 5501:5500
      volumes:
        - ./setup-scripts:/opt/oracle/scripts/setup
        - ./oradata:/opt/oracle/oradata
      environment:
        - ORACLE_PWD=Change0nInstall
```

Bringing the stack up:

```
$ docker-compose up
Docker Compose is now in the Docker CLI, try `docker compose up`

Creating network "12c-compose_default" with the default driver
Creating 12c-compose_db_1 ... done
Attaching to 12c-compose_db_1
db_1  | ORACLE PASSWORD FOR SYS, SYSTEM AND PDBADMIN: Change0nInstall
db_1  |
db_1  | LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 06-MAY-2021 17:32:35
<SNIP>
db_1  | Executing user defined scripts
db_1  | /opt/oracle/runUserScripts.sh: running /opt/oracle/scripts/setup/shell.sh
db_1  | Bilbo was here
db_1  | 
db_1  | /opt/oracle/runUserScripts.sh: running /opt/oracle/scripts/setup/sysdate.sql
db_1  | 
db_1  | SYSDATE
db_1  | ---------
db_1  | 06-MAY-21
db_1  | 
db_1  | DONE: Executing user defined scripts
db_1  | 
db_1  | The Oracle base remains unchanged with value /opt/oracle
db_1  | #########################
db_1  | DATABASE IS READY TO USE!
db_1  | #########################
```

Note that:
- `setup-scripts` are only run at DB creation time, so the first time you do an `up`
- Same for setting the password
- `oracle` won't be accepted as a valid password
