### ISSUE TITLE
Enable Java Remote Debugging

### ISSUE THREAD

**Issue by stephan2012** [oracle/docker-images#213]
Is there any (standard) way to enable Java Remote Debugging for the managed server container? Setting
```yaml
  managedserver:
    environment:
    - PRODUCTION_MODE=false
    - DEBUG_FLAG=true
```
works for the Admin server only but not for the managed server. Passing something like ```-Xrunjdwp:transport=dt_socket,address=7777,server=y,suspend=n``` in JAVA_OPTIONS or USER_MEM_ARGS causes the managed server container to fail startup because options will be applied to both, Node Manager and Managed Server, which results in port conflicts.
