### ISSUE TITLE
Limit fix is not being applied for 21.3.0 Express

### ISSUE THREAD

**Issue by NickLarsenNZ** [oracle/docker-images#2243]
This line isn't doing anything because the file is still named with the old version:

https://github.com/oracle/docker-images/blob/1cd62e6cb0803cd3f76d672f623c201af41caecd/OracleDatabase/SingleInstance/dockerfiles/21.3.0/Dockerfile.xe#L70

```
[oracle@sample-oracle-express-0 /]$ ls /etc/security/limits.d
20-nproc.conf  oracle-database-preinstall-18c.conf
```

**Comment by abhisbyk** [comment]
@NickLarsenNZ unable to reproduced on my setup. I have `oracle-database-preinstall-21c.conf` itself. My log:
```
abhisbyk@mac~  docker images
REPOSITORY                                                                       TAG                 IMAGE ID            CREATED             SIZE
oracle                                                                           21c-xe              eceaae0499bd        6 hours ago         6.68GB
oraclelinux                                                                      7-slim              5fe1636f17bb        9 months ago        132MB
golang                                                                           1.15                874f8671ee4e        10 months ago       840MB

04:31:20
abhisbyk@mac ~  docker ps -a
CONTAINER ID        IMAGE                                                                       COMMAND                  CREATED             STATUS                 PORTS                                            NAMES
c8e73e826bc6        oracle:21c-xe                                                               "/bin/sh -c 'exec $O…"   4 hours ago         Up 4 hours (healthy)   0.0.0.0:9038->1521/tcp                           xe

04:31:37
abhisbyk@mac ~  docker exec -it xe /bin/bash
bash-4.2$
bash-4.2$ ls /etc/security/limits.d
20-nproc.conf  oracle-database-preinstall-21c.conf
bash-4.2$
bash-4.2$
```

I created a fresh 21c XE image and checked, seems alright. Can you share more info on how the image is built ?

**Comment by NickLarsenNZ** [comment]
Hmm, okay, I wonder if I've mis-tagged something. I'll do a clean build from scratch. Apologies for not double checking @abhisbyk

**Comment by NickLarsenNZ** [comment]
It seems I had somehow been running the 18c XE image.

I'm now running the correct image:

```
bash-4.2$ ls /etc/security/limits.d
20-nproc.conf  oracle-database-preinstall-21c.conf
```

However, I still get a `su: cannot open session: Permission denied` on startup. I'll do some more digging to see if this issue should be closed or not.

**Comment by NickLarsenNZ** [comment]
It works if I set the following on the container:

```yml
        securityContext:
          privileged: true
```

**Comment by NickLarsenNZ** [comment]
My rendered kustomize is:

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oracle-express
    app.kubernetes.io/version: 21c
  name: test-oracle-express-env-6ct58987ht
---
apiVersion: v1
data:
  0001.sql: |
    SELECT 1 FROM dual;
    ALTER SYSTEM SET db_create_file_dest = '/opt/oracle/oradata';
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oracle-express
    app.kubernetes.io/version: 21c
  name: test-oracle-setup-kgm92hbmmt
---
apiVersion: v1
data:
  0001-provision-schema.sql: |
    -- private sql statements here
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oracle-express
    app.kubernetes.io/version: 21c
  name: test-oracle-startup-t45tbcbb4t
---
apiVersion: v1
data:
  ORACLE_PWD: ...
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oracle-express
    app.kubernetes.io/version: 21c
  name: test-oracle-express-env-hgtmkb944b
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oracle-express
    app.kubernetes.io/version: 21c
  name: test-oracle-express
spec:
  clusterIP: None
  ports:
  - name: oracle
    port: 1521
    protocol: TCP
    targetPort: listener
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oracle-express
    app.kubernetes.io/version: 21c
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oracle-express
    app.kubernetes.io/version: 21c
  name: test-oracle-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: oracle-express
      app.kubernetes.io/version: 21c
  serviceName: test-oracle-express
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: oracle-express
        app.kubernetes.io/version: 21c
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: test-oracle-express-env-6ct58987ht
        - secretRef:
            name: test-oracle-express-env-hgtmkb944b
        image: my-registry/oracle-express:21.3.0
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - |-
                /bin/echo -en 'shutdown abort;
                ' | env ORACLE_SID=${ORACLE_SID^^} sqlplus -S / as sysdba
        name: oracle-express
        ports:
        - containerPort: 1521
          name: listener
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'if [ -f $ORACLE_BASE/checkDBLockStatus.sh ]; then $ORACLE_BASE/checkDBLockStatus.sh
              ; else $ORACLE_BASE/checkDBStatus.sh; fi '
          initialDelaySeconds: 20
          periodSeconds: 40
          timeoutSeconds: 20
        resources:
          limits:
            cpu: 2000m
            memory: 8Gi
          requests:
            cpu: 750m
            memory: 2Gi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /opt/oracle/oradata
          name: data
        - mountPath: /docker-entrypoint-initdb.d/setup/
          name: init-setup
        - mountPath: /docker-entrypoint-initdb.d/startup/
          name: init-startup
        - mountPath: /opt/oracle/diag
          name: diagnostics
      imagePullSecrets: []
      securityContext:
        fsGroup: 54321
        runAsUser: 54321
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          name: test-oracle-setup-kgm92hbmmt
        name: init-setup
      - configMap:
          name: test-oracle-startup-t45tbcbb4t
        name: init-startup
      - emptyDir: {}
        name: diagnostics
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: oracle-express
        app.kubernetes.io/version: 21c
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 25Gi
      storageClassName: gp2

```
