### ISSUE TITLE
Security context is broken for 21.3.0 Express

### ISSUE THREAD

**Issue by NickLarsenNZ** [oracle/docker-images#2244]
I've been having trouble running the 21.3.0 XE container due to permission issues. 
I'm not using Helm, but basically the same manifest and saw the following:

https://github.com/oracle/docker-images/blob/1cd62e6cb0803cd3f76d672f623c201af41caecd/OracleDatabase/SingleInstance/helm-charts/oracle-db/templates/deployment.yaml#L31-L33

I've had to do the following instead:

```yml
      securityContext:
        runAsUser: 0   # the scripts are only runnable by root
        fsGroup: 54321 # the scripts `su - oracle` which tries to mkdir on the mounted volume
```

Thought it might be useful to note here in case anyone else is struggling.

**Comment by NickLarsenNZ** [comment]
Well that works up until here: 

https://github.com/oracle/docker-images/blob/1cd62e6cb0803cd3f76d672f623c201af41caecd/OracleDatabase/SingleInstance/dockerfiles/21.3.0/runUserScripts.sh#L30

Because it's being run as root (due to my `securityContext` change), but it need to run as `oracle`.

**Comment by NickLarsenNZ** [comment]
I think there needs to be a `chown` (or move the `USER` statement above the `RUN` maybe), so that we can go back to running as `oracle` as intended.

https://github.com/oracle/docker-images/blob/1cd62e6cb0803cd3f76d672f623c201af41caecd/OracleDatabase/SingleInstance/dockerfiles/21.3.0/Dockerfile.xe#L63-L81

**Comment by abhisbyk** [comment]
I am unable to reproduce this on my setup. Used the following yaml file to deploy 21c XE database:
```
apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-xe-oradata
  namespace: ns1
  labels:
    app: oracle-xe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-xe
  labels:
    app: oracle-xe
  namespace: ns1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-xe
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracle-xe
    spec:
      securityContext:
        runAsUser: 54321
        fsGroup: 54321
      containers:
        - name: xe
          image: <Latest 21c XE image location>
          envFrom:
            - secretRef:
                name: oracle-xe-credentials
          ports:
            - containerPort: 1521
              name: oracle-listener
            - containerPort: 5500
              name: oem-express
          volumeMounts:
          - name: oradata
            mountPath: /opt/oracle/oradata
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            exec:
              command:
                - /bin/sh
                - "-c"
                - $ORACLE_BASE/$CHECK_DB_FILE
      volumes:
        - name: oradata
          persistentVolumeClaim:
            claimName: oracle-xe-oradata
---
apiVersion: v1
kind: Service
metadata:
  name: xe-database
  namespace: ns1
  labels:
    app: oracle-xe
spec:
  ports:
    - name: listener
      port: 1521
      targetPort: oracle-listener
  selector:
    app: oracle-xe

```


The status after deploying this on k8s cluster:
```
$: xe-deployment kubectl get all -n ns1
NAME                             READY   STATUS    RESTARTS   AGE
pod/oracle-xe-65fbcd6665-8kbvl   1/1     Running   0          16m

NAME                  TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/xe-database   ClusterIP   10.96.27.81   <none>        1521/TCP   16m

NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/oracle-xe   1/1     1            1           16m

NAME                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/oracle-xe-65fbcd6665   1         1         1       16m
```
