### ISSUE TITLE
Oracle Database with NFS mounted Volume

### ISSUE THREAD

**Issue by lexwinko** [oracle/docker-images#2452]
I'm trying to deploy an oracle enterprise database on our internal docker swarm and ran into the following issue:

The docker-compose is run by our manager node as 
`docker stack deploy -c /etc/docker/X/X/oracle/docker-compose.yml X --with-registry-auth`

Inside the compose file we have an NFS mounted volume on a different node (excempt):
```
services:
  oracle:
    volumes:
      - qa_oracle:/opt/oracle/oradata
volumes:
  oracle:
    driver_opts:
      type: nfs
      o: addr=X,nolock,soft,rw
      device: ":/mnt/swarm_persistence/shared/X/oracle"
```

When I try to run the container, I get the same error as in https://github.com/oracle/docker-images/issues/2395 , but currently there is no way to create a local oracle image to test whether that fix would work.

I added the oracle user with uid 54321 to our storage server and gave ownership of the folder
![image](https://user-images.githubusercontent.com/60097568/188843344-f5e4002c-9a0d-4f00-8cac-2fd2aadf0939.png)

What am I doing wrong?
