### ISSUE TITLE
Setup script ignored if using image container-registry.oracle.com/database/express:21.3.0-xe

### ISSUE THREAD

**Issue by usharik** [oracle/docker-images#2599]
Hello! I use a local Oracle Express DB run by docker-compose with this configuration
```
version: '3'
services:
  oracledb:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./local-dev-env/setup-database.sh:/opt/oracle/scripts/setup/setup-database.sh
    environment:
      - ORACLE_PWD=manager
    ports:
      - "1521:1521"
      - "5000:5000"
volumes:
  oracle_data:
```
Problem is that setup script is never run also if I drop all the volumes by `docker-compose down -v`
As far as I can see the setup script is run in case there is no database created and that is checked by this condition in `runOracle.sh`

```
if [ -f "$ORACLE_BASE"/oradata/.${ORACLE_SID}"${CHECKPOINT_FILE_EXTN}" ] && [ -d "$ORACLE_BASE"/oradata/"${ORACLE_SID}" ]; then
```

So only data from `/oradata` used here and nothing else shall be mounted as volumes here
As far as I can see all is done as it's described here

https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md

What could be a problem? Why setup script is ignored?

**Comment by gvenzl** [comment]
Hi @usharik,

Thanks for using these images!

I'm pretty sure you are not supposed to map files as volumes but only directories.

Could you try with:

```
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./local-dev-env:/opt/oracle/scripts/setup
```

Note that it doesn't include `setup-database.sh` on either side.

**Comment by usharik** [comment]
Hello. It if I map startup script this way it works

**Comment by usharik** [comment]
@IshaanDesai45 why did you close the issue? It's no resolved.

Just checked the mount from inside the container and file is mounted as file. Here is a proof
```
➜  project-home git:(master) ✗ docker-compose -f docker-compose.yaml exec oracledb bash
bash-4.2$ cd /opt/oracle/scripts/startup/
bash-4.2$ pwd
/opt/oracle/scripts/startup
bash-4.2$ ls -la
total 16
drwxr-xr-x 1 oracle oinstall 4096 Mar 23 22:02 .
drwxr-xr-x 1 oracle oinstall 4096 Sep 30 04:18 ..
-rw-r--r-- 1    501 games     280 Mar 23 11:34 create-dfis-db-user.sh
bash-4.2$ 

```

**Comment by oraclesean** [comment]
The script's executable bit and ownership will prevent it from running.

**Comment by IshaanDesai45** [comment]
yup the file will be mounted by your way . But it won't be executed so please try the mounting the directory which contains the setup script instead. 
Volume Mapping in the docker compose would look like 
```
volumes:
      - oracle_data:/opt/oracle/oradata
      - ./local-dev-env:/opt/oracle/scripts/setup
```

**Comment by usharik** [comment]
Why the absolutely same startup script is running? Why there are no error messages because of insufficient permissions?
As I understand all user scripts are run by this script 
https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/dockerfiles/21.3.0/runUserScripts.sh

I don't see any log message from there in DB startup log. At least `Executing user defined scripts` shall be there but it's not.

**Comment by oraclesean** [comment]
`runUserScripts.sh` expects `SCRIPTS_ROOT` to be a directory containing scripts:
> ```
> # Execute custom provided files (only if directory exists and has files in it)
> if [ -d "$SCRIPTS_ROOT" ] && [ -n "$(ls -A "$SCRIPTS_ROOT")" ]; then
> ```
The mounted file isn't a script; this step fails.

**Comment by gvenzl** [comment]
Scripts in `setup` are only executed once after the database setup:

```
   -v /opt/oracle/scripts/startup | /docker-entrypoint-initdb.d/startup
                  Optional: A volume with custom scripts to be run after database startup.
                  For further details see the "Running scripts after setup and on startup" section below.
   -v /opt/oracle/scripts/setup | /docker-entrypoint-initdb.d/setup
                  Optional: A volume with custom scripts to be run after database setup.
                  For further details see the "Running scripts after setup and on startup" section below.
```

If you already have an existing database inside your volume, setup scripts will no longer be executed.
I assume this is the case here and why the scripts run when put into `startup` but not into `setup`.

Do you already have an existing database in the volume?

**Comment by usharik** [comment]
@gvenzl the command `docker-compose down -v` stops all applications and removes all the volumes so I don't have any database configured

**Comment by IshaanDesai45** [comment]
@usharik the problem here is that you are using docker volumes 
First keep in mind that 21.3.0-xe image comes with a pre-configured DB 

So there are two types of volumes that can be used for database persistence with the image 
1. Docker Volume - When using docker volume; the prebuiltdb (already setup/configured) from the image is copied into the docker volume
2. Host Directory - When using host directory for database persistence ; a new database is configured in the host directory 

Right now you are creating a docker volume and mounting that to the `/opt/oracle/oradata` which results in copying of database files from image to the docker volume and no new db is setup hence setup scripts are not called. 
So you can create a host directory and give is write permission instead and then try docker compose
```
mkdir -p <host_dir_loc>
chmod 777 <host_dir_loc>
```
and then change the docker compose file to 

```
version: '3'
services:
  oracledb:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    volumes:
      - <host_dir_loc>:/opt/oracle/oradata
      - ./local-dev-env/setup-database.sh:/opt/oracle/scripts/setup/setup-database.sh
    environment:
      - ORACLE_PWD=manager
    ports:
      - "1521:1521"
      - "5000:5000"
```
This is start configuring/setting up a new database and will execute the setup scripts

P.S - This is also covered in the documentation under "Mounting Docker volume/host directory for database persistence"
