### ISSUE TITLE
[FATAL] [DBT-06608] The specified audit file destination (/opt/oracle/admin/ORCLCDB/adump) is not writable.

### ISSUE THREAD

**Issue by TalelKaroui** [oracle/docker-images#2816]
I am facing an ERROR [FATAL] [DBT-06608] The specified audit file destination (/opt/oracle/admin/ORCLCDB/adump) is not writable.
when want to build my container by using this commande line 

`docker-compose up -d --build`
And this is the log file : 

> [2024:06:14 12:58:27]: Acquiring lock .ORCLCDB.create_lck with heartbeat 30 secs
> [2024:06:14 12:58:27]: Lock acquired
> [2024:06:14 12:58:27]: Starting heartbeat
> [2024:06:14 12:58:27]: Lock held .ORCLCDB.create_lck
> ORACLE EDITION: ENTERPRISE
> 
> LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 14-JUN-2024 12:58:27
> 
> Copyright (c) 1991, 2019, Oracle.  All rights reserved.
> 
> Starting /opt/oracle/product/19c/dbhome_1/bin/tnslsnr: please wait...
> 
> TNSLSNR for Linux: Version 19.0.0.0.0 - Production
> System parameter file is /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
> Log messages written to /opt/oracle/diag/tnslsnr/43c7149b6156/listener/alert/log.xml
> Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
> Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
> 
> Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
> STATUS of the LISTENER
> ------------------------
> Alias                     LISTENER
> Version                   TNSLSNR for Linux: Version 19.0.0.0.0 - Production
> Start Date                14-JUN-2024 12:58:27
> Uptime                    0 days 0 hr. 0 min. 0 sec
> Trace Level               off
> Security                  ON: Local OS Authentication
> SNMP                      OFF
> Listener Parameter File   /opt/oracle/product/19c/dbhome_1/network/admin/listener.ora
> Listener Log File         /opt/oracle/diag/tnslsnr/43c7149b6156/listener/alert/log.xml
> Listening Endpoints Summary...
>   (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
>   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
> The listener supports no services
> The command completed successfully
> [WARNING] [DBT-06208] The 'SYS' password entered does not conform to the Oracle recommended standards.
>    CAUSE:
> a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
> b.The password entered is a keyword that Oracle does not recommend to be used as password
>    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
> [WARNING] [DBT-06208] The 'SYSTEM' password entered does not conform to the Oracle recommended standards.
>    CAUSE:
> a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
> b.The password entered is a keyword that Oracle does not recommend to be used as password
>    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
> [WARNING] [DBT-06208] The 'PDBADMIN' password entered does not conform to the Oracle recommended standards.
>    CAUSE:
> a. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9].
> b.The password entered is a keyword that Oracle does not recommend to be used as password
>    ACTION: Specify a strong password. If required refer Oracle documentation for guidelines.
> [FATAL] [DBT-06608] The specified audit file destination (/opt/oracle/admin/ORCLCDB/adump) is not writable.
>    ACTION: Ensure that the audit file destination (/opt/oracle/admin/ORCLCDB/adump) is writable.
> cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB/ORCLCDB.log: No such file or directory
> cat: /opt/oracle/cfgtoollogs/dbca/ORCLCDB.log: No such file or directory

**Configuration :**
----------------------------------------
**compose.yml file**
-----------------------------------------
```
version: '3.1'
services:
  oracle-db:
    #image: container-registry.oracle.com/database/enterprise:19.3.0.0
    build:
      dockerfile: ora.Dockerfile
    container_name: oracle-db
    environment:
      - ORACLE_SID=ORCLCDB   #Oracle instance SID - change here
      - ORACLE_PDB=ORCLPDB1  #Oracle PDB name - change here
      - ORACLE_CHARACTERSET=WE8ISO8859P15
      - ORACLE_PWD=admin123  #Oracle sys/system password - change here
      - NLS_LENGTH_SEMANTICS=CHAR
      - TZ=Europe/Paris      #Oracle TimeZone setup
      # Optional parameters
      #- ORACLE_MEMORY: 3GB             # Total memory target for the database
      #- ORACLE_PGA_TARGET: 1GB        # PGA memory target
      #- ORACLE_AGGREGATE_LIMIT: 2GB
    ports:
      - 1521:1521
    volumes:
      # Shared place between host and container - change the path if different
      - c:\Temp\Docker\Oracle\oracle-db-data:/opt/oracle/admin
    networks:
      - oracle_network

networks:
  oracle_network:
    driver: bridge
```
-----------------------------------------
**ora.Dockerfile**
```
FROM container-registry.oracle.com/database/enterprise:19.3.0.0

COPY files/oracle/scripts/ /opt/oracle/scripts/startup/
COPY files/oracle/patch/zoneinfo/ $ORACLE_HOME/oracore/zoneinfo/
RUN mkdir dmp_files && chmod 766 dmp_files/
COPY dmp_files/* dmp_files/

```

I am using Rancher desktop 1.14.1
and this is the information of Docker:

`docker context ls
NAME        DESCRIPTION                               DOCKER ENDPOINT                  ERROR
default *   Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine`

```
`docker info      
Client:
 Version:    26.1.0-rd
 Context:    default
 Debug Mode: false

Server:
 Containers: 25
  Running: 18
  Paused: 0
  Stopped: 7
 Images: 12
 Server Version: 25.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 4e1fe7492b9df85914c389d1f15a3ceedbb280ac
 runc version: 51d5e94601ceffbbd85688df1c928ecccbfa4685
 init version:
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.153.1-microsoft-standard-WSL2
 Operating System: Rancher Desktop WSL Distribution
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.607GiB
 Name: FRA-BFSJQL3
 ID: 7fc860ef-6a41-42e0-ba6d-afb73db82809
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support`
```
