### ISSUE TITLE
Latest Oracle Database 23ai Free image not working with podman on GitHub Actions

### ISSUE THREAD

**Issue by rob975** [oracle/docker-images#2925]
Latest free image fails to start using podman on GitHub Actions with the error:
```
Password: su: Authentication failure
```

It works fine with docker.

23.6 image worked with podman too.

This is the test I used:
```yaml
jobs:
  test-oracle-free:
    strategy:
      fail-fast: false
      matrix:
        tag: [23.6.0.0-lite, latest-lite]
        runtime: [docker, podman]
    runs-on: ubuntu-latest
    steps:
      - run: >-
          ${{ matrix.runtime }} run -d --name oracle-db
          container-registry.oracle.com/database/free:${{ matrix.tag }}
      - run: sleep 60
      - run: |
          echo "::group::Logs"
          ${{ matrix.runtime }} logs oracle-db
          echo "::endgroup::"
          status=$(${{ matrix.runtime }} inspect -f "{{.State.Status}}" oracle-db)
          [[ $status = "running" ]] && exit 0 || exit 1
```
