### ISSUE TITLE
dpdump deleted on initial startup

### ISSUE THREAD

**Issue by AlBundy33** [oracle/docker-images#2933]
with this docker-compose file the dumps in the dpdump-folder will be deleted on first startup.
```
services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=oracle
    volumes:
      - ./oradata:/opt/oracle/oradata
      - ./startup:/opt/oracle/scripts/startup
      - ./setup:/opt/oracle/scripts/setup
      - ./dpdump:/opt/oracle/admin/XE/dpdump
```
folders are owned by 54321:54321
