### ISSUE TITLE
Running Docker Oracle Database in Kubernetes fails

### ISSUE THREAD

**Issue by eldada** [oracle/docker-images#328]
I built the Docker image from version [12.2.0.1](https://github.com/oracle/docker-images/tree/master/OracleDatabase/dockerfiles/12.2.0.1).
The build was fine. Ran it on my Mac successfully. My application was able to connect to it without a problem.
The command I used to run on my mac was
```
docker run -d --name oracle -p 1521:1521 -p 5500:5500 -e ORACLE_SID=ORADB -v ~/.oracle:/opt/oracle/oradata oracle/database:12.2.0.1-se2
```

I then moved to running it on a Kubernetes cluster I have in GCP.
My yaml files looks like this
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oracle.eldadtestsabcoracle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oracle.eldadtestsabcoracle
    spec:
      containers:
      - name: db-eldadtestsabcoracle
        image: my-docker-registry/oracle-database:12.2.0.1-se2
        env:
        - name: ORACLE_SID
          value: ORADB
        ports:
        - containerPort: 1521
      imagePullSecrets:
      - name: docker-reg-secret
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
  - port: 1521
    protocol: TCP
  selector:
    app: oracle.eldadtestsabcoracle
```

When I deploy it, it comes up with many errors and crashes
```
ORACLE AUTO GENERATED PASSWORD FOR SYS, SYSTEM AND PDBAMIN: 6CF/CNMYz2s=1

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 21-MAR-2017 06:15:52

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/oracle/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                21-MAR-2017 06:15:52
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/oracle/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[FATAL] [DBT-06103] The port (5,500) is already in use.
   ACTION: Specify a free port.
[WARNING] [DBT-10102] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
   CAUSE: The database should be registered with a listener in order to access the EM DB Express URL.
   ACTION: Select a listener to be registered or created with the database.
cat: /opt/oracle/cfgtoollogs/dbca/ORADB/ORADB.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ORADB.log: No such file or directory

SQL*Plus: Release 12.2.0.1.0 Production on Tue Mar 21 06:16:00 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Connected to an idle instance.

SQL>    ALTER SYSTEM SET control_files='/opt/oracle/oradata/ORADB/control01.ctl' scope=spfile
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL>    ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> Disconnected
mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/spfileORADB.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/orapwORADB': No such file or directory
#########################
DATABASE IS READY TO USE!
#########################
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining

```

Any ideas?
