### ISSUE TITLE
DB XE "ORA-01034: ORACLE not available:" while executing sqlplus.

### ISSUE THREAD

**Issue by GrigorievNick** [oracle/docker-images#670]
In image inside scripts `runOracle.sh`,
A lot of command like 
`sqlplus / as sysdba` or `su -p oracle -c "sqlplus / as sysdba @file"` or `su -p oracle -c "$ORACLE_HOME/bin/sqlplus / as sysdba @$f";`
All this command return 
```
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0
```
is this bug? that url specified as `/` but must be lime user/password@connect url.
Or i do something wrong.
PS.
I build Oracle Xe from oracle-xe-11.2.0-1.0.x86_64.rpm.zip
And us  oracle/instantclient/12.2.0.1  for this.
Start with docker compose like 
```
version: '2'
services:
  database:
    shm_size: 1G
    image: oracle/database:11.2.0.2-xe
    environment:
      - ORACLE_SID=xe
      - ORACLE_PDB=test
      - ORACLE_PWD=test
    volumes:
      - ./oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
      - ./data-bridge:/data-bridge # just to have someplace to put data into the running container if needed
      - ./initscripts:/u01/app/oracle/scripts/startup # please here init scripts
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    networks:
      - dev
networks:
  dev:
    driver: bridge
```
