### ISSUE TITLE
Trying to run WebLogic Cluster in Docker Swarm based off of 1221-docker-compose sample

### ISSUE THREAD

**Issue by forestoden6** [oracle/docker-images#852]
I've run into a problem attempting to get a WLS Cluster running through Docker Swarm. When trying to access the `sample` web page on the managed server I receive a Connection Refused error. 

Please let me know if this is out of scope for here, but I would appreciate any help.

**Swarm Setup**
I have three Vagrant boxes running Ubuntu 16.04 in a private network, meaning they should have full network access to each other. I've run other swarms on this setup without issue.

**Docker Compose**
As the Docker Compose sample [(here)](https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/1221-docker-compose/docker-compose.yml) is incompatible with Swarm, I've upgraded the version and made a few changes. Here is my current `docker-compose.yml` file

```
version: '3.6'

networks:
  wlsnet:

services:

  # Deploys the AdminServer with default hostname 'wlsadmin' used by scripts in 1221-domain.
  wlsadmin:
    image: 10.0.3.2:5000/1221-appdeploy
    #container_name: wlsadmin
    ports:
      - "7001:7001"
    networks:
      wlsnet:

  # Deploys a container running a Managed Server and a Node Manager to control MS from AdminServer
  managedserver:
    image: 10.0.3.2:5000/1221-appdeploy
    command: createServer.sh
    ports:
      - "7002:7002"
    networks:
      wlsnet:
    depends_on:
      - adminserver
```

I am able to run this using `docker-compose up -d` on a single host and have no issues accessing the Admin Console or the sample webpage on both the Admin and Managed Servers.

**Docker Swarm**
When I take this `docker-compose.yml` file and run it using Docker Swarm using the command `docker stack deploy -c docker-compose.yml apptier` I do not get any errors from Docker or within the WebLogic server logs. Both the Admin and Managed Servers start up and say they are serving requests. 

I am able to access the Admin Server (exposed on port 7001) and can connect to `<ip>:7001/console` as well as the sample.war through ` curl http://10.0.3.2:7001/sample/`, giving me the following output

```
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>WebLogic on Docker - Request Information</h1>
        <ul>
            <li>getVirtualServerName(): WL_AdminServer</li>
            <li>InetAddress.hostname: 86b161a0a7b6</li>
            <li>InetAddress.serverAddress: 86b161a0a7b6/10.0.0.6</li>
            <li>getLocalAddr(): 10.255.0.24</li>
            <li>getLocalName(): 10.255.0.24</li>
            <li>getLocalPort(): 7001</li>
            <li>getServerName(): 10.0.3.2</li>
            <li>WLS Server Name: WL_AdminServer</li>
            <li>getIpAddOfCurrSrv():  </li>
        </ul>
    </body>
</html>
```

However trying to access the Managed Server gives me a Connection Refused

```
vagrant@1221-docker-compose$ curl http://10.0.3.2:7002/sample/
curl: (7) Failed to connect to 10.0.3.2 port 7002: Connection refused
```

I did a `docker inspect` everywhere I could to ensure ports were binding and being exposed and saw nothing that seemed wrong to me. The last thing I tried has left me perplexed. From inside the Admin Server container, I tried to curl the managed server using the hostname, and this worked.

```
bash-4.2# curl http://apptier_managedserver:7002/sample/

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>WebLogic on Docker - Request Information</h1>
        <ul>
            <li>getVirtualServerName(): ManagedServer-Payxg4@3a3636beb1bc</li>
            <li>InetAddress.hostname: 3a3636beb1bc</li>
            <li>InetAddress.serverAddress: 3a3636beb1bc/10.0.0.9</li>
            <li>getLocalAddr(): 10.0.0.9</li>
            <li>getLocalName(): 3a3636beb1bc</li>
            <li>getLocalPort(): 7002</li>
            <li>getServerName(): apptier_managedserver</li>
            <li>WLS Server Name: ManagedServer-Payxg4@3a3636beb1bc</li>
            <li>getIpAddOfCurrSrv():  </li>
        </ul>
    </body>
</html>
```

At this point, I see two potential places this error could be occurring. Because only the managed server runs `createServer.sh`, something in this script is causing problems exposing the service to outside the Swarm. I tried looking through the code but wasn't able to pick anything out, but I noticed there are a lot of hardcoded values that may cause issues when run in a Swarm. The other option would be somewhere in Docker Swarm's networking, but this seems less likely.

Again, please tell me if this is out of scope here as I've deviated a bit from the given samples.
